name: Tournament availability

on:
  schedule:
    - cron: "0 0 */2 * *" # Runs every 2 days at midnight UTC
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Create .env file for the script to get secrets
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "EMAIL_RECIPIENT=${{ secrets.EMAIL_RECIPIENT }}" >> .env
          echo "CITY=${{ secrets.CITY }}" >> .env
          echo "RADIUS=${{ secrets.RADIUS }}" >> .env

      - name: Run Playwright Tests
        run: npx playwright test --project='chromium'
